# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f5e21664286c9488f3584740a2b6010b642b6d66001778ecd42efa16419bf8029a586f51bbd0179f4ad5da1ca3da7ca2e8eac2ae92bda1856566e889fcb1ba8

test:
  secret_key_base: 1d42af0bd6119932deaa418cc91ba24d64642677a207390f8c3458f4e8761ce0d3273403b12a4821ea517da2d92b2c83626cae5ca48489a4f0ce4241aa308c28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
